[tasks.build]
description = "Build x64emu"
category = "Build"
command = "cargo"
args = ["build", "--all-features", "-${@}"]
dependencies = ["bios"]

[tasks.test]
description = "Test x64emu"
category = "Test"
command = "cargo"
args = ["test", "--all-features", "-${@}"]
dependencies = ["bios", "sample"]

[tasks.bios]
description = "Build bios"
category = "Build"
command = "make"
args = ["-C", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/src/bios"]

[tasks.sample]
description = "Sample kernel"
category = "Build"
command = "make"
args = ["-C", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/tests/kernel"]

[tasks.clean]
category = "Clean"
command = "cargo"
args = ["clean"]

[tasks.default]
alias = "build"