name: x64emu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - uses: davidB/rust-cargo-make@v1
    - uses: ilammy/setup-nasm@v1
    - name: Install libc6 dev for i386
      run: sudo apt install libc6-dev-i386

    - uses: actions/checkout@v2
    - name: Build
      run: cargo make build -verbose
    - name: Run tests
      run: cargo make test -verbose
